spring.application.name=seguridadcalidad
backend.base-url=${BACKEND_URL:http://localhost:8081}
logging.level.com.duoc.seguridadcalidad=INFO
logging.level.org.springframework.web=INFO
logging.level.org.springframework.http=INFO
logging.file.path=./logs
