spring.application.name=backend
server.port=8081

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# DataSource (compatible local + docker)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/mydatabase}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Logs (ajustados)
logging.level.org.springframework.web=debug
logging.level.org.hibernate=debug

logging.file.name=backend.log

app.security.migrate-plain-passwords=false